name: pr-check
  
on:
  workflow_dispatch:
  pull_request:
    types: [ 'opened', 'synchronize' ]
  push:  
    branches:  
      - main

permissions:
  contents: write
  pull-requests: read
  statuses: write
  security-events: write

  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
    - name: Install Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
      with:
        go-version-file: 'go.mod'
    - name: Setup latest Terraform  
      uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
      with:
        terraform_wrapper: false
    - name: Remove generated directory  
      run: rm -rf generated
    - name: Run go mod tidy
      run: go mod tidy
    - name: generate schemas
      run: |
        go run cmd/main.go -refresh true
        go mod tidy
    - name: Run tests for generated package
      run: go test github.com/${{ github.repository }}/v6/generated/...
    - name: Run Gosec Security Scanner
      uses: securego/gosec@d4617f51baf75f4f809066386a4f9d27b3ac3e46 #2.21.4
      with:
        args: '-exclude=G101 ./...'
    - name: Run GolangCI-Lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
      with:
        version: latest
        skip-cache: true
    - name: Initialize CodeQL
      uses: github/codeql-action/init@4f3212b61783c3c68e8309a0f18a699764811cda # v3.27.1
      with:
        languages: "go"
    - name: Autobuild
      uses: github/codeql-action/autobuild@4f3212b61783c3c68e8309a0f18a699764811cda # v3.27.1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@4f3212b61783c3c68e8309a0f18a699764811cda # v3.27.1
